name: textlint
on: [pull_request]
jobs:
  textlint:
    name: run textlint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
          registry-url: 'https://registry.npmjs.org'
      - name: package install
        run: yarn
      - name: textlint
        run: yarn run textlint